version: "3.8"


services:
  handwriting:
    build: .
    # image: handwriting
    restart: always
    labels:
      traefik.enable: true
      traefik.http.services.stream-svc.loadbalancer.server.port: 8001
      traefik.http.routers.stream-rtr.rule: Host("magma.ai-adesso.de")
      traefik.http.routers.stream-rtr.service: stream-svc
      traefik.http.routers.stream-rtr.entrypoints: https
      # traefik.http.middlewares.stream-strippath.stripprefix.prefixes: /stream
      # traefik.http.routers.stream-rtr.middlewares: stream-strippath
    networks:
      - web

networks:
  web:
    name: traefik_web
    external: true
